# Generated by Django 6.0.3 on 2026-04-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='PagoSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('aliados', 'Aliados'), ('oxxo', 'Oxxo'), ('paynet', 'Paynet')], max_length=10)),
                ('numero_contrato', models.CharField(max_length=50)),
                ('interes', models.DecimalField(decimal_places=4, max_digits=16)),
                ('impuesto', models.DecimalField(decimal_places=4, max_digits=16)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_sat', to='reconciliacion.periodo')),
            ],
            options={
                'verbose_name': 'Pago SAT',
                'verbose_name_plural': 'Pagos SAT',
                'indexes': [models.Index(fields=['periodo', 'canal'], name='reconciliac_periodo_01fa6f_idx'), models.Index(fields=['numero_contrato'], name='reconciliac_numero__163906_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuotaMexico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('aliados', 'Aliados'), ('oxxo', 'Oxxo'), ('paynet', 'Paynet')], max_length=10)),
                ('numero_contrato', models.CharField(max_length=50)),
                ('interes', models.DecimalField(decimal_places=4, max_digits=16)),
                ('impuesto', models.DecimalField(decimal_places=4, max_digits=16)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='reconciliacion.periodo')),
            ],
            options={
                'verbose_name': 'Cuota Mexico',
                'verbose_name_plural': 'Cuotas Mexico',
                'indexes': [models.Index(fields=['periodo', 'canal'], name='reconciliac_periodo_a766b7_idx'), models.Index(fields=['numero_contrato'], name='reconciliac_numero__6a1d2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResultadoReconciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('faltante', 'Pago Faltante'), ('de_mas', 'Pago de Mas'), ('completo', 'Pago Completo')], max_length=10)),
                ('canal', models.CharField(choices=[('aliados', 'Aliados'), ('oxxo', 'Oxxo'), ('paynet', 'Paynet')], max_length=10)),
                ('numero_contrato', models.CharField(max_length=50)),
                ('interes', models.DecimalField(decimal_places=4, max_digits=16)),
                ('impuesto', models.DecimalField(decimal_places=4, max_digits=16)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='reconciliacion.periodo')),
            ],
            options={
                'verbose_name': 'Resultado Reconciliacion',
                'verbose_name_plural': 'Resultados Reconciliacion',
                'indexes': [models.Index(fields=['periodo', 'tipo', 'canal'], name='reconciliac_periodo_4a8b3a_idx')],
            },
        ),
    ]
